#!/usr/bin/env python

""" 
Hackish script to list the dependencies of a pyx file.
As long as it doesn't miss anything, it's okay to be sloppy.
"""    

import sys, os, re

base  = sys.argv[1]
fname = base + '.pyx'

lines = [line for line in re.sub(r'\\\n',' ',open(fname).read()).split('\n')
         if 'cimport' in line]

deps = [os.path.basename(base)]
for line in lines:
    m = re.match(r'cimport\s+(.*)', line)
    imps = []
    if m:
        imps = [re.sub('\sas\s.*','',x).strip() 
                for x in m.groups()[0].split(',')]
    else:
        m = re.match(r'from\s+(.*)\scimport', line)
        if m:
            imps = [m.groups()[0]]
    deps.extend([imp.replace('.','/') for imp in imps])

print fname
bdir = os.path.dirname(base)
for d in deps:
    dpath = os.path.join(bdir, d+'.pxd')
    if os.path.exists(dpath): print dpath
